name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Dynamically Create the Task Definition
      - name: Create ECS Task Definition
        id: create-task-def
        run: |
          cat <<EOF > taskdefinition.json
          {
            "family": "${{ secrets.ECS_TASK_FAMILY }}",
            "containerDefinitions": [
              {
                "name": "${{ secrets.ECS_CONTAINER_NAME }}",
                "image": "${{ secrets.ECS_IMAGE }}",
                "memory": ${{ secrets.ECS_MEMORY }},
                "cpu": ${{ secrets.ECS_CPU }},
                "essential": true,
                "portMappings": [
                  {
                    "containerPort": 80,
                    "hostPort": 80
                  }
                ]
              }
            ]
          }
          EOF

      # Step 4: Register the Task Definition
      - name: Register Task Definition
        id: register-task-def
        run: |
          TASK_DEFINITION_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://taskdefinition.json \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)
          echo "TASK_DEFINITION_ARN=${TASK_DEFINITION_ARN}" >> $GITHUB_ENV

      # Step 5: Update the ECS Service
      - name: Update ECS Service
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER }} \
            --service ${{ secrets.ECS_SERVICE }} \
            --task-definition ${{ env.TASK_DEFINITION_ARN }} \
            --region ${{ secrets.AWS_REGION }}
